version: '3.7'
    
services:
  family:
    container_name: family-container
    build:
      context: .
    ports:
      - 8072:8072
      - 8000:8000
    environment:
      - SERVER_PORT=8072
      - POSTGRES_URL=jdbc:postgresql://pg_db:5432/AG3D
      - POSTGRES_USER=family
      - POSTGRES_PASSWORD=family123456
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=docker -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  pg_db:
    container_name: pg_db_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=AG3D
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT:-5432}:5432
      