CREATE SCHEMA family
    AUTHORIZATION postgres;
CREATE ROLE family WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'family123456';
GRANT CREATE, USAGE ON SCHEMA family TO family;